site_name: My Docs
docs_dir: docs

theme:
  name: readthedocs

nav:
  - はじめに: index.md
  - ドキュメント:
      - データ構造用ライブラリ: data.md
      - 数学用ライブラリ: math.md
      - 標準入力用ライブラリ: stdio.md

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: false
      use_pygments: false
      noclasses: true
  - toc:
      permalink: true

extra_css:
  - css/ex_style.css
