site_name: AtCoder Library
docs_dir: docs

theme:
  name: material
  language: ja

nav:
  - はじめに: index.md
  - ドキュメント:
      - データ構造用ライブラリ: data.md
      - 数学用ライブラリ: math.md
      - 標準入力用ライブラリ: stdio.md
  - その他: other.md

markdown_extensions:
  - admonition
  - meta
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.keys
  - def_list
  - codehilite:
      linenums: true
      guess_lang: true
      use_pygments: false
      noclasses: true
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized

extra:
  search:
    language: 'jp'

extra_css:
  - css/ex_style.css